/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContabilidadeRouteImport } from './routes/contabilidade'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as TiRouteImport } from './routes/ti'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadeRoute = ContabilidadeRouteImport.update({
  id: '/contabilidade',
  path: '/contabilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const TiRoute = TiRouteImport.update({
  id: '/ti',
  path: '/ti',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contabilidade': typeof ContabilidadeRoute
  '/financas': typeof FinancasRoute
  '/manutencao': typeof ManutencaoRoute
  '/ti': typeof TiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contabilidade': typeof ContabilidadeRoute
  '/financas': typeof FinancasRoute
  '/manutencao': typeof ManutencaoRoute
  '/ti': typeof TiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contabilidade': typeof ContabilidadeRoute
  '/financas': typeof FinancasRoute
  '/manutencao': typeof ManutencaoRoute
  '/ti': typeof TiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contabilidade' | '/financas' | '/manutencao' | '/ti'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contabilidade' | '/financas' | '/manutencao' | '/ti'
  id: '__root__' | '/' | '/contabilidade' | '/financas' | '/manutencao' | '/ti'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContabilidadeRoute: typeof ContabilidadeRoute
  FinancasRoute: typeof FinancasRoute
  ManutencaoRoute: typeof ManutencaoRoute
  TiRoute: typeof TiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidade': {
      id: '/contabilidade'
      path: '/contabilidade'
      fullPath: '/contabilidade'
      preLoaderRoute: typeof ContabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ti': {
      id: '/ti'
      path: '/ti'
      fullPath: '/ti'
      preLoaderRoute: typeof TiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContabilidadeRoute: ContabilidadeRoute,
  FinancasRoute: FinancasRoute,
  ManutencaoRoute: ManutencaoRoute,
  TiRoute: TiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
